-- CREATE TABLE sections (
--     id SERIAL PRIMARY KEY,
--     course_id INT REFERENCES courses(id) ON DELETE CASCADE,
--     title VARCHAR(300) NOT NULL,
--     "order" INT DEFAULT 0,
--     created_at TIMESTAMPTZ DEFAULT NOW(),
--     modified_at TIMESTAMPTZ DEFAULT NOW()
-- );