-- CREATE TABLE enrollments (
--     id SERIAL PRIMARY KEY,
--     student_id INT REFERENCES users(id) ON DELETE CASCADE,
--     course_id INT REFERENCES courses(id) ON DELETE CASCADE,
--     enrolled_at TIMESTAMPTZ DEFAULT NOW()
-- );