-- CREATE TABLE videos (
--     id SERIAL PRIMARY KEY,
--     section_id INT REFERENCES sections(id) ON DELETE CASCADE,
--     title VARCHAR(300) NOT NULL,
--     video_file VARCHAR(255) NOT NULL,
--     "order" INT DEFAULT 0,
--     created_at TIMESTAMPTZ DEFAULT NOW(),
--     modified_at TIMESTAMPTZ DEFAULT NOW()
-- );